python:
  build: python/flask
  command: python app.py
  ports:
    - "5000:5000"
ruby:
  build: ruby
  command: bundle exec ruby sinatra.rb -o '0.0.0.0'
  ports:
    - "4567:4567"
go:
  build: go
  command: go run martini.go
  ports:
    - "3000:3000"
node:
  build: node/express
  command: npm start
  ports:
    - "8080:8080"
